# Generated by Django 3.0.7 on 2020-06-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='level',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], max_length=32, null=True, verbose_name='레벨'),
        ),
    ]
