# Generated by Django 3.0.7 on 2020-06-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_fcuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='level',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=32, verbose_name='레벨'),
            preserve_default=False,
        ),
    ]
